services:
  postgres:
    image: postgres
    container_name: jeweler-postgres
    environment:
      - POSTGRES_DB=jeweler-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: