//This would ideally be updated frequently by tracking the user agent strings of incoming requests

export const distroMockData = [
  { name: 'aix', version: '7.2' },
  { name: 'amigaos', version: '3.2' },
  { name: 'arch', version: '2024.04.01' },
  { name: 'centos', version: '9' },
  { name: 'chromiumos', version: '14850.64.0' },
  { name: 'contiki', version: '4.0' },
  { name: 'fedora', version: 'F39' },
  { name: 'freebsd', version: '13.1' },
  { name: 'debian', version: '11.3' },
  { name: 'deepin', version: '20.3' },
  { name: 'dragonfly', version: '6.0.1' },
  { name: 'elementaryos', version: '6.1' },
  { name: 'gentoo', version: '2024.04.23' },
  { name: 'ghostbsd', version: '21.09' },
  { name: 'gnu', version: '0.99.2' },
  { name: 'haiku', version: 'hrev55714' },
  { name: 'harmonyos', version: '2.0.0' },
  { name: 'hp-ux', version: '11iv3' },
  { name: 'hurd', version: '0.9' },
  { name: 'joli', version: '1.2.3' },
  { name: 'linpus', version: '2.2.4' },
  { name: 'linspire', version: '10.0.0' },
  { name: 'linux', version: '5.16.12' },
  { name: 'maemo', version: '6.0' },
  { name: 'mageia', version: '8.3' },
  { name: 'mandriva', version: '2021' },
  { name: 'manjaro', version: '21.2.1' },
  { name: 'meego', version: '1.2.0' },
  { name: 'minix', version: '3.4.0' },
  { name: 'mint', version: '20.3' },
  { name: 'morphos', version: '3.15' },
  { name: 'netbsd', version: '9.2' },
  { name: 'openeos', version: '2023.4.5' },
  { name: 'openbsd', version: '7.0' },
  { name: 'opensuse', version: 'Tumbleweed' },
  { name: 'openvms', version: '9.2-2' },
  { name: 'palm', version: 'webOS 3.0.5' },
  { name: 'pclinuxos', version: '2022.10' },
  { name: 'plan9', version: 'Fourth Edition' },
  { name: 'raspbian', version: '2022-01-28' },
  { name: 'redhat', version: '9.0.0' },
  { name: 'sabayon', version: '22.01' },
  { name: 'sailfish', version: '4.2.0.21' },
  { name: 'serenityos', version: '0.10.2' },
  { name: 'slackware', version: '15.0' },
  { name: 'solaris', version: '11.4' },
  { name: 'suse', version: '15.4' },
  { name: 'tizen', version: '5.5' },
  { name: 'ubuntu', version: '23.10' },
  { name: 'vectorlinux', version: '8.2' },
  { name: 'webos', version: '3.0.5' },
  { name: 'zenwalk', version: '15.0' },
];
